version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    ports:
      - "8080:80"
    networks:
      - laravel_network
    depends_on:
      - mysql
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=8889
      - DB_DATABASE=CERTIF
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_TEST_DATABASE=:memory:
      - DB_TEST_CONNECTION=sqlite

  mysql:
    image: mysql:latest
    container_name: penc-api-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CERTIF
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8889:8889"
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: penc-api-phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge