version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    ports:
      - "8080:80"
    networks:
      - laravel_network
    depends_on:
      - mysql
  
  mysql:
    image: mysql:latest
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CERTIF
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8889:8889"
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: penc-api-phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge